### ISSUE TITLE
Make primenet.py work per-directory

### ISSUE THREAD

**Issue by selroc** [tdulcet/Distributed-Computing-Scripts#13]
Synopsis: to allow multiple job types with one script run.

Hypothetical steps:

- Allow multiple --dir options
- Require two parameters for each --dir option: 1) work directory; 2) work type
- Typical usage should look like, for example: --dir /home/user/work1 PRP --dir /home/user/work2 PRP_DC

**Comment by tdulcet** [comment]
I see you are requesting the same `--dirs` option as is in the PrimeNet script included with GpuOwl, although with an additional worktype parameter.

Porting that option is actually my top priority after I finish testing the PRP proof uploading (#12). Although, getting different work types on different CPU cores or GPUs would be a separate issue: https://github.com/tdulcet/Distributed-Computing-Scripts/blob/66de4840e271e482188fa9c92b72bc436505b9a9/README.md#L208-L209
In Python with the [optparse module](https://docs.python.org/3/library/optparse.html), one can only have a single parameter per option, so unfortunately, your proposal would not work. In addition, our PrimeNet script currently supports slightly different worktype mnemonics: https://github.com/tdulcet/Distributed-Computing-Scripts/blob/66de4840e271e482188fa9c92b72bc436505b9a9/primenet.py#L698-L699
I would be open to supporting the GpuOwl ones if there were interest in that, although this would also be a separate issue.

Anyway, using your example, I think the usage would be something like this: ` --workdir /home/user/ --dir work1 --dir work2`, which users could shorten to: ` -w ~ -D work1 -D work2`.

**Comment by selroc** [comment]
One possible solution to the optparse module limitation is to couple options positionally. So in this case it would be:

`-w ~ -D work1 -T 150 -D work2 -T 151`

which obviously means: dir work1 worktype 150, dir work2 worktype 151.

**Comment by tdulcet** [comment]
Yes, that would be a solution. Although as I said, updating the existing `-T/--worktype` option would be a separate issue, as it would require first adding support for setting per thread/directory options and I am also not sure how much interest there would be in it. Pull requests are of course welcome! For this issue, I will likely add a `-D/--dir` option, similar to the `--dirs` option in the script included with GpuOwl.

For now, it may be easier for you to just run a separate instance of the script for each directory, particularly if you are using it with different GPUs.

**Comment by tdulcet** [comment]
@selroc - I added a `-D/--dir` option in https://github.com/tdulcet/Distributed-Computing-Scripts/commit/b4ae3ca31a09638530eb46233021b658902cb212. The output still needs to be improved so that it is more clear which directory/worker/job it is referring to, but I will handle that in a future update. Feel free to create a new issue for your requested changes to the existing `-T/--worktype` option.
