### ISSUE TITLE
--no_more_work not working

### ISSUE THREAD

**Issue by selroc** [tdulcet/Distributed-Computing-Scripts#16]
I have run primenet.py with --no_more_work but still it is getting new exponents to compute.
Please fix.

**Comment by tdulcet** [comment]
I am sorry to hear you are having an issue. However, I just tested the `--no_more_work` option and it worked as expected for me.

Are you using the latest version of the PrimeNet script? After using the option, was `NoMoreWork = 1` added to your `local.ini` config file?

**Comment by selroc** [comment]
Yes it is there.

**Comment by selroc** [comment]
I will try redownloading the script.

**Comment by tdulcet** [comment]
OK, I presume the latest version is working for you. Please reopen this issue if you still have any problems.
