### ISSUE TITLE
check sum typo

### ISSUE THREAD

**Issue by akruchko** [tdulcet/Distributed-Computing-Scripts#2]
Hi

md5sum in the file cudalucas.sh is SUM="424ca4c9dfcfc8f16de1408ef9d970c5".
According to https://www.mersenneforum.org/mayer/README.html#download md5 checksum = a3ab997df7d7246b29e47a851088d2a5 for mlucas_v18.txz.

Could you check, please?

Thanks

**Comment by tdulcet** [comment]
Not a typo, the md5sum was correct for the [Mar 5, 2019 version](https://web.archive.org/web/20190407203538/https://www.mersenneforum.org/mayer/README.html#download), but it seems that they released a updated [Apr 3, 2019 version](https://www.mersenneforum.org/mayer/README.html#download) with the same filename. Usually when they release a new version, they update the filename so as not to break scripts like this.

Thanks for pointing out the issue! I will update the scripts with the new md5sum.

**Comment by akruchko** [comment]
Great, thanks.
